name: Build And Deploy

on:
  push:
    branches:
      - prod
      - test
      - dev

jobs:
  deploy:
    name: Build and Deploy
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Extract branch name
        run: echo "ENV_NAME=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV

      - name: Print local env
        run: make print-env

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-skip-session-tagging: true
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY_ID }}
          aws-region: ca-central-1

      - name: Build and deploy
        run: make build-and-deploy
        env:
          GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
          GOOGLE_SECRET: ${{ secrets.GOOGLE_SECRET }}
