name: API PR checks

on:
  pull_request:
    paths:
      - api/**

jobs:
  checks:
    name: Checks
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Build
        run: make build-api

      - name: Jest run
        working-directory: api
        run: yarn test
