name: App PR checks

on:
  pull_request:
    paths:
      - app/**

jobs:
  checks:
    name: Checks
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Build
        run: make build-app

      - name: Lint
        working-directory: app
        run: yarn lint
